trigger:
  batch: true
  branches:
    include:
    - '*'

pool:
  vmImage: macOS-12

steps:
  - checkout: self
  - task: NuGetToolInstaller@1
    displayName: 'Use NuGet'
    inputs:
      checkLatest: true
  - task: NuGetCommand@2
    displayName: nuget restore
    inputs:
      command: 'restore'
      restoreSolution: 'Laerdal.Dfu.Bindings.Android/Laerdal.Dfu.Bindings.Android.csproj'
  - task: MSBuild@1
    displayName: MSBuild
    inputs:
      solution: Laerdal.Dfu.Bindings.Android/Laerdal.Dfu.Bindings.Android.csproj
      configuration: Release

  - publish: $(Build.ArtifactStagingDirectory)
    artifact: output
  - publish: $(Build.SourcesDirectory)
    artifact: source