<?xml version="1.0" encoding="utf-8"?>

<!--                                                                                                                       -->
<!--  Local build (macOS or Windows):                                                                                      -->
<!--                                                                                                                       -->
<!--      dotnet msbuild Laerdal.Scripts/Laerdal.Builder.targets /m:1                                                      -->
<!--                                                                                                                       -->
<!--  To specify an explicit version:                                                                                      -->
<!--                                                                                                                       -->
<!--      dotnet msbuild Laerdal.Scripts/Laerdal.Builder.targets /m:1 /p:Laerdal_Version_Full=2.9.0.0                      -->
<!--                                                                                                                       -->
<Project DefaultTargets="BuildProjects">

    <PropertyGroup>
        <Configuration Condition=" '$(Configuration)' == '' ">Release</Configuration>

        <PackageOutputPath Condition=" '$(PackageOutputPath)' == '' ">$([System.IO.Path]::Combine($(MSBuildThisFileDirectory), '..', 'Artifacts/'))</PackageOutputPath>

        <Laerdal_Project Condition=" '$(Laerdal_Project)' == '' ">$([System.IO.Path]::Combine($(MSBuildThisFileDirectory), '..', 'Laerdal.Dfu.Bindings.Android', 'Laerdal.Dfu.Bindings.Android.csproj'))</Laerdal_Project>

        <!-- version: {Nordic_Package_Version}.{build_number}   override with /p:Laerdal_Version_Full=... -->
        <Nordic_Package_Version Condition=" '$(Nordic_Package_Version)' == '' ">2.9.0</Nordic_Package_Version>
        <Laerdal_Revision Condition=" '$(Laerdal_Revision)' == '' and '$(GITHUB_RUN_NUMBER)' != '' ">$([MSBuild]::Add(43857, $(GITHUB_RUN_NUMBER)))</Laerdal_Revision>
        <Laerdal_Revision Condition=" '$(Laerdal_Revision)' == '' ">0</Laerdal_Revision>
        <Laerdal_Version_Full Condition=" '$(Laerdal_Version_Full)' == '' ">$(Nordic_Package_Version).$(Laerdal_Revision)</Laerdal_Version_Full>
    </PropertyGroup>

    <Target Name="BuildProjects">
        <Error Condition=" '$(Configuration)'     == '' " Text="'Configuration' must be set." />
        <Error Condition=" '$(Laerdal_Project)'   == '' " Text="'Laerdal_Project' must be set." />
        <Error Condition=" '$(PackageOutputPath)' == '' " Text="'PackageOutputPath' must be set." />

        <PropertyGroup>
            <_Params>Configuration=$(Configuration)</_Params>
            <_Params>$(_Params);PackageOutputPath=$(PackageOutputPath)</_Params>
            <_Params>$(_Params);Laerdal_Version_Full=$(Laerdal_Version_Full)</_Params>
        </PropertyGroup>

        <MSBuild Projects="$(Laerdal_Project)" Properties="$(_Params)" Targets="Clean"/>
        <MSBuild Projects="$(Laerdal_Project)" Properties="$(_Params)" Targets="Restore"/>
        <!-- _DownloadAndroidNativeFiles + BuildingProject=true must be called explicitly for the pipeline to work correctly -->
        <MSBuild Projects="$(Laerdal_Project)" Properties="$(_Params);BuildingProject=true" Targets="_DownloadAndroidNativeFiles"/>
        <!-- BuildingProject=false ensures the nuget correctly binds over to the underlying jars/aars -->
        <MSBuild Projects="$(Laerdal_Project)" Properties="$(_Params);BuildingProject=false" Targets="Build"/>
    </Target>

</Project>
